# Generated by Django 4.0.3 on 2022-03-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
